### PR TITLE
Addition of a few commands

### PR DESCRIPTION
**Pull request by LuisPavelA**

### CODE REVIEW

**Comment by X-Legendary** [comment]
Great PR, thanks for contributing! I will read through it tomorrow, merge it, and deploy it.

**Comment by X-Legendary** [comment]
Hi, I have reviewed your PR, and it seems you haven't loaded the commands. Please import each command, and add them in the commands object in `src/commands/index.js` like shown below:

```js
import yourCommand from "./yourCommand"

const commands = {
    // Every command is new line, just so it looks clean
    yourCommand
}

export default commands

**Comment by LuisPavelA** [comment]
Done!

**Comment by X-Legendary** [comment]
Thank you, I'll merge this right away.

**Pull request merged**
